import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { JSDOM } from "jsdom";

// if (typeof document === "undefined") {
//   const dom = new JSDOM("<!doctype html><html><body></body></html>");
//   global.document = dom.window.document;
//   global.Element = dom.window.Element;
// }

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
